baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: $CRAFT_SITE_NAME
primary: true
siteGroup: 0d89c679-f6f5-42ae-8341-4bea917c6af7 # $CRAFT_SITE_NAME
sortOrder: 1
