dateModified: 1695913487
email:
  fromEmail: info@putyourlightson.net
  fromName: 'Craft Coding Challenge'
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0b13c242-c4bf-4365-b5d1-fd1fe51676d8: 'Public Schema' # Public Schema
    0d89c679-f6f5-42ae-8341-4bea917c6af7: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    3bf95c07-7e41-44a1-b44f-92605fde2f53: Homepage # Homepage
    29ccb1bf-c99b-448f-8112-2bb043cfcd38: Homepage # Homepage
    0779f354-f5d2-4f82-9a36-28a252f70ce4: 'Public Schema' # Public Schema
    31006d4c-2f40-498c-9a4c-69cff4fd4279: Common # Common
    66852952-995b-48aa-bfcc-cf15779bb315: 'Tailwind UI' # Tailwind UI
    b20879ea-009b-4b7e-95f8-a0c50603fb43: Default # Default
    b55012be-3f7f-4150-b59c-5a6623c00743: 'Public Schema' # Public Schema
    c5fb341d-e1f2-4874-8e3d-541c2260935c: Pages # Pages
    c7c2807b-84cc-4e1f-9279-af044bc0b472: 'Public Schema' # Public Schema
    f255ef6d-0c55-4bdc-9ced-f610bbb3bed6: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
system:
  edition: pro
  live: true
  name: $CRAFT_SITE_NAME
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
