name: Build and Push Docker Images
on:
  push:
    paths:
      - .docker-config/spin-up-craft-base/*
      - .docker-config/spin-up-craft-base-dev/*
    tags:
      - '*.*.*'
  workflow_dispatch:
jobs:
  build-php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ["8.0", "8.1", "8.2"]
        images: ["spin-up-craft-base", "spin-up-craft-base-dev"]
    name: ${{ matrix.images }} ${{ matrix.php }} images
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build .docker-config/nystudio107/${{ matrix.images }}:${{ matrix.php }}-alpine
        uses: docker/build-push-action@v4
        with:
          context: .docker-config/${{ matrix.images }}/php-${{ matrix.php }}-alpine
          file: .docker-config/${{ matrix.images }}/php-${{ matrix.php }}-alpine/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: nystudio107/${{ matrix.images }}:${{ matrix.php }}-alpine
          build-args: |
            PHP_VERSION=${{ matrix.php }}
